<?php

/**
 * @file
 * Ads Catalan Countries and regions to Backdrop's countries list.
 */

/**
 * Implements hook_countries_alter()
 *
 * @param array $countries
 * @return void
 */
function catalan_countries_countries_alter(&$countries) {
  $countries['PC'] = 'Països Catalans';
  asort($countries);
}

/**
 * Implements hook_addressfield_address_formats_alter()
 *
 * @param array $address_formats
 * @return void
 */
function catalan_countries_addressfield_address_formats_alter(&$address_formats) {
  $address_formats['PC'] = array(
    'used_fields' => array('locality', 'administrative_area', 'postal_code'),
    'required_fields' => array('locality', 'administrative_area', 'postal_code'),
    'administrative_area_label' => 'Comarca',
    'render_administrative_area_value' => TRUE,
  );
}

/**
 * Implements hook_addressfield_administrative_areas_alter()
 *
 * @param array $administrative_areas
 * @return void
 */
function catalan_countries_addressfield_administrative_areas_alter(&$administrative_areas) {
  $administrative_areas['PC'] = array(
    // Catalunya (Principat) - 43 comarques
    'AC' => 'Alt Camp',
    'AE' => 'Alt Empordà',
    'APe' => 'Alt Penedès',
    'AU' => 'Alt Urgell',
    'AR' => 'Alta Ribagorça',
    'AN' => 'Anoia',
    'VN' => 'Aran',
    'BG' => 'Bages',
    'BC' => 'Baix Camp',
    'BE' => 'Baix Ebre',
    'BEm' => 'Baix Empordà',
    'BLl' => 'Baix Llobregat',
    'BPe' => 'Baix Penedès',
    'Ba' => 'Barcelonès',
    'Ber' => 'Berguedà',
    'Cer' => 'Cerdanya',
    'CB' => 'Conca de Barberà',
    'Ga' => 'Garraf',
    'Gar' => 'Garrigues',
    'Gx' => 'Garrotxa',
    'Gi' => 'Gironès',
    'Ll' => 'Lluçanès',
    'Ma' => 'Maresme',
    'Mo' => 'Moianès',
    'Mon' => 'Montsià',
    'No' => 'Noguera',
    'Os' => 'Osona',
    'PJ' => 'Pallars Jussà',
    'PS' => 'Pallars Sobirà',
    'PE' => 'Pla de l\'Estany',
    'PU' => 'Pla d\'Urgell',
    'Pr' => 'Priorat',
    'RE' => 'Ribera d\'Ebre',
    'Ri' => 'Ripollès',
    'Sg' => 'Segarra',
    'Se' => 'Segrià',
    'Sv' => 'Selva',
    'So' => 'Solsonès',
    'Ta' => 'Tarragonès',
    'TA' => 'Terra Alta',
    'Ur' => 'Urgell',
    'VO' => 'Vallès Occidental',
    'VOr' => 'Vallès Oriental',

    // Franja de ponent
    'Bci' => 'Baix Cinca',
    'Ll' => 'Llitera',
    'Mat' => 'Matarranya',
    'Rib' => 'Ribagorça',

    // País Valencià - 34 comarques
    'Al' => 'Alacantí',
    'Alt' => 'Alcalatén',
    'Alc' => 'Alcoià',
    'AM' => 'Alt Maestrat',
    'APa' => 'Alt Palància',
    'AV' => 'Alt Vinalopó',
    'BM' => 'Baix Maestrat',
    'BS' => 'Baix Segura',
    'BV' => 'Baix Vinalopó',
    'CM' => 'Camp de Morvedre',
    'CT' => 'Camp de Túria',
    'CN' => 'Canal de Navarrés',
    'Co' => 'Comtat',
    'Cos' => 'Costera',
    'FB' => 'Foia de Bunyol',
    'HN' => 'Horta Nord',
    'HS' => 'Horta Sud',
    'MAl' => 'Marina Alta',
    'MBa' => 'Marina Baixa',
    'PAl' => 'Plana Alta',
    'PBa' => 'Plana Baixa',
    'PUR' => 'Plana d\'Utiel-Requena',
    'Po' => 'Ports',
    'RA' => 'Racó d\'Ademús',
    'RAl' => 'Ribera Alta',
    'RB' => 'Ribera Baixa',
    'Sa' => 'Safor',
    'Ser' => 'Serrania',
    'Val' => 'València',
    'VdA' => 'Vall d\'Albaida',
    'VdC' => 'Vall de Cofrents-Aiora',
    'VM' => 'Vinalopó Mitjà',

    // Illes Balears - 5 comarques
    'Ei' => 'Eivissa',
    'For' => 'Formentera',
    'Lle' => 'Llevant',
    'Men' => 'Menorca',
    'Mit' => 'Mitjorn',
    'Cab' => 'Cabrera',
    'Pal' => 'Palma',
    'PM' => 'Pla de Mallorca',
    'RR' => 'Raiguer',
    'ST' => 'Serra de Tramuntana',

    // Catalunya del Nord - 5 comarques
    'ACe' => 'Alta Cerdanya',
    'Cap' => 'Capcir',
    'Conf' => 'Conflent',
    'Fen' => 'Fenolleda',
    'Ros' => 'Rosselló',
    'Vs' => 'Vallespir',

    // L'Alguer (Sardenya) - ciutat
    'Alg' => 'l\'Alguer',
  );
}
